/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as DoctorIndexRouteImport } from './routes/doctor.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VideoIdRouteImport } from './routes/video.$id'
import { Route as PrescriptionIdRouteImport } from './routes/prescription.$id'
import { Route as PatientProfileRouteImport } from './routes/patient.profile'
import { Route as PatientPrescriptionsRouteImport } from './routes/patient.prescriptions'
import { Route as PatientDoctorsRouteImport } from './routes/patient.doctors'
import { Route as PatientAppointmentsRouteImport } from './routes/patient.appointments'
import { Route as DoctorProfileRouteImport } from './routes/doctor.profile'
import { Route as DoctorPostsRouteImport } from './routes/doctor.posts'
import { Route as DoctorCareCoordinationRouteImport } from './routes/doctor.care-coordination'
import { Route as DoctorAppointmentsRouteImport } from './routes/doctor.appointments'
import { Route as AuthPatientRouteImport } from './routes/auth.patient'
import { Route as AuthDoctorRouteImport } from './routes/auth.doctor'
import { Route as AuthAdminRouteImport } from './routes/auth.admin'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminDoctorsRouteImport } from './routes/admin.doctors'
import { Route as AdminCareCoordinationRouteImport } from './routes/admin.care-coordination'
import { Route as AdminAppointmentsRouteImport } from './routes/admin.appointments'
import { Route as PatientDoctorsIdRouteImport } from './routes/patient.doctors.$id'
import { Route as PatientBookDoctorIdRouteImport } from './routes/patient.book.$doctorId'
import { Route as DoctorPrescriptionIdRouteImport } from './routes/doctor.prescription.$id'

const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRoute,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VideoIdRoute = VideoIdRouteImport.update({
  id: '/video/$id',
  path: '/video/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionIdRoute = PrescriptionIdRouteImport.update({
  id: '/prescription/$id',
  path: '/prescription/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientProfileRoute = PatientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PatientRoute,
} as any)
const PatientPrescriptionsRoute = PatientPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => PatientRoute,
} as any)
const PatientDoctorsRoute = PatientDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAppointmentsRoute = PatientAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => PatientRoute,
} as any)
const DoctorProfileRoute = DoctorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorPostsRoute = DoctorPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorCareCoordinationRoute = DoctorCareCoordinationRouteImport.update({
  id: '/care-coordination',
  path: '/care-coordination',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorAppointmentsRoute = DoctorAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => DoctorRoute,
} as any)
const AuthPatientRoute = AuthPatientRouteImport.update({
  id: '/auth/patient',
  path: '/auth/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDoctorRoute = AuthDoctorRouteImport.update({
  id: '/auth/doctor',
  path: '/auth/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/auth/admin',
  path: '/auth/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDoctorsRoute = AdminDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCareCoordinationRoute = AdminCareCoordinationRouteImport.update({
  id: '/care-coordination',
  path: '/care-coordination',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AdminRoute,
} as any)
const PatientDoctorsIdRoute = PatientDoctorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PatientDoctorsRoute,
} as any)
const PatientBookDoctorIdRoute = PatientBookDoctorIdRouteImport.update({
  id: '/book/$doctorId',
  path: '/book/$doctorId',
  getParentRoute: () => PatientRoute,
} as any)
const DoctorPrescriptionIdRoute = DoctorPrescriptionIdRouteImport.update({
  id: '/prescription/$id',
  path: '/prescription/$id',
  getParentRoute: () => DoctorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/doctor': typeof DoctorRouteWithChildren
  '/patient': typeof PatientRouteWithChildren
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/care-coordination': typeof AdminCareCoordinationRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/doctor': typeof AuthDoctorRoute
  '/auth/patient': typeof AuthPatientRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/care-coordination': typeof DoctorCareCoordinationRoute
  '/doctor/posts': typeof DoctorPostsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/doctors': typeof PatientDoctorsRouteWithChildren
  '/patient/prescriptions': typeof PatientPrescriptionsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/prescription/$id': typeof PrescriptionIdRoute
  '/video/$id': typeof VideoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/doctor/prescription/$id': typeof DoctorPrescriptionIdRoute
  '/patient/book/$doctorId': typeof PatientBookDoctorIdRoute
  '/patient/doctors/$id': typeof PatientDoctorsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/care-coordination': typeof AdminCareCoordinationRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/doctor': typeof AuthDoctorRoute
  '/auth/patient': typeof AuthPatientRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/care-coordination': typeof DoctorCareCoordinationRoute
  '/doctor/posts': typeof DoctorPostsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/doctors': typeof PatientDoctorsRouteWithChildren
  '/patient/prescriptions': typeof PatientPrescriptionsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/prescription/$id': typeof PrescriptionIdRoute
  '/video/$id': typeof VideoIdRoute
  '/admin': typeof AdminIndexRoute
  '/doctor': typeof DoctorIndexRoute
  '/patient': typeof PatientIndexRoute
  '/doctor/prescription/$id': typeof DoctorPrescriptionIdRoute
  '/patient/book/$doctorId': typeof PatientBookDoctorIdRoute
  '/patient/doctors/$id': typeof PatientDoctorsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/doctor': typeof DoctorRouteWithChildren
  '/patient': typeof PatientRouteWithChildren
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/care-coordination': typeof AdminCareCoordinationRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/doctor': typeof AuthDoctorRoute
  '/auth/patient': typeof AuthPatientRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/care-coordination': typeof DoctorCareCoordinationRoute
  '/doctor/posts': typeof DoctorPostsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/doctors': typeof PatientDoctorsRouteWithChildren
  '/patient/prescriptions': typeof PatientPrescriptionsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/prescription/$id': typeof PrescriptionIdRoute
  '/video/$id': typeof VideoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/doctor/prescription/$id': typeof DoctorPrescriptionIdRoute
  '/patient/book/$doctorId': typeof PatientBookDoctorIdRoute
  '/patient/doctors/$id': typeof PatientDoctorsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/doctor'
    | '/patient'
    | '/admin/appointments'
    | '/admin/care-coordination'
    | '/admin/doctors'
    | '/admin/payments'
    | '/admin/posts'
    | '/admin/reviews'
    | '/admin/users'
    | '/auth/admin'
    | '/auth/doctor'
    | '/auth/patient'
    | '/doctor/appointments'
    | '/doctor/care-coordination'
    | '/doctor/posts'
    | '/doctor/profile'
    | '/patient/appointments'
    | '/patient/doctors'
    | '/patient/prescriptions'
    | '/patient/profile'
    | '/prescription/$id'
    | '/video/$id'
    | '/admin/'
    | '/doctor/'
    | '/patient/'
    | '/doctor/prescription/$id'
    | '/patient/book/$doctorId'
    | '/patient/doctors/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/appointments'
    | '/admin/care-coordination'
    | '/admin/doctors'
    | '/admin/payments'
    | '/admin/posts'
    | '/admin/reviews'
    | '/admin/users'
    | '/auth/admin'
    | '/auth/doctor'
    | '/auth/patient'
    | '/doctor/appointments'
    | '/doctor/care-coordination'
    | '/doctor/posts'
    | '/doctor/profile'
    | '/patient/appointments'
    | '/patient/doctors'
    | '/patient/prescriptions'
    | '/patient/profile'
    | '/prescription/$id'
    | '/video/$id'
    | '/admin'
    | '/doctor'
    | '/patient'
    | '/doctor/prescription/$id'
    | '/patient/book/$doctorId'
    | '/patient/doctors/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/doctor'
    | '/patient'
    | '/admin/appointments'
    | '/admin/care-coordination'
    | '/admin/doctors'
    | '/admin/payments'
    | '/admin/posts'
    | '/admin/reviews'
    | '/admin/users'
    | '/auth/admin'
    | '/auth/doctor'
    | '/auth/patient'
    | '/doctor/appointments'
    | '/doctor/care-coordination'
    | '/doctor/posts'
    | '/doctor/profile'
    | '/patient/appointments'
    | '/patient/doctors'
    | '/patient/prescriptions'
    | '/patient/profile'
    | '/prescription/$id'
    | '/video/$id'
    | '/admin/'
    | '/doctor/'
    | '/patient/'
    | '/doctor/prescription/$id'
    | '/patient/book/$doctorId'
    | '/patient/doctors/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DoctorRoute: typeof DoctorRouteWithChildren
  PatientRoute: typeof PatientRouteWithChildren
  AuthAdminRoute: typeof AuthAdminRoute
  AuthDoctorRoute: typeof AuthDoctorRoute
  AuthPatientRoute: typeof AuthPatientRoute
  PrescriptionIdRoute: typeof PrescriptionIdRoute
  VideoIdRoute: typeof VideoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/video/$id': {
      id: '/video/$id'
      path: '/video/$id'
      fullPath: '/video/$id'
      preLoaderRoute: typeof VideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescription/$id': {
      id: '/prescription/$id'
      path: '/prescription/$id'
      fullPath: '/prescription/$id'
      preLoaderRoute: typeof PrescriptionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/profile': {
      id: '/patient/profile'
      path: '/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof PatientProfileRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/prescriptions': {
      id: '/patient/prescriptions'
      path: '/prescriptions'
      fullPath: '/patient/prescriptions'
      preLoaderRoute: typeof PatientPrescriptionsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/doctors': {
      id: '/patient/doctors'
      path: '/doctors'
      fullPath: '/patient/doctors'
      preLoaderRoute: typeof PatientDoctorsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/appointments': {
      id: '/patient/appointments'
      path: '/appointments'
      fullPath: '/patient/appointments'
      preLoaderRoute: typeof PatientAppointmentsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/doctor/profile': {
      id: '/doctor/profile'
      path: '/profile'
      fullPath: '/doctor/profile'
      preLoaderRoute: typeof DoctorProfileRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/posts': {
      id: '/doctor/posts'
      path: '/posts'
      fullPath: '/doctor/posts'
      preLoaderRoute: typeof DoctorPostsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/care-coordination': {
      id: '/doctor/care-coordination'
      path: '/care-coordination'
      fullPath: '/doctor/care-coordination'
      preLoaderRoute: typeof DoctorCareCoordinationRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/appointments': {
      id: '/doctor/appointments'
      path: '/appointments'
      fullPath: '/doctor/appointments'
      preLoaderRoute: typeof DoctorAppointmentsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/auth/patient': {
      id: '/auth/patient'
      path: '/auth/patient'
      fullPath: '/auth/patient'
      preLoaderRoute: typeof AuthPatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/doctor': {
      id: '/auth/doctor'
      path: '/auth/doctor'
      fullPath: '/auth/doctor'
      preLoaderRoute: typeof AuthDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/admin': {
      id: '/auth/admin'
      path: '/auth/admin'
      fullPath: '/auth/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/doctors': {
      id: '/admin/doctors'
      path: '/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AdminDoctorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/care-coordination': {
      id: '/admin/care-coordination'
      path: '/care-coordination'
      fullPath: '/admin/care-coordination'
      preLoaderRoute: typeof AdminCareCoordinationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/patient/doctors/$id': {
      id: '/patient/doctors/$id'
      path: '/$id'
      fullPath: '/patient/doctors/$id'
      preLoaderRoute: typeof PatientDoctorsIdRouteImport
      parentRoute: typeof PatientDoctorsRoute
    }
    '/patient/book/$doctorId': {
      id: '/patient/book/$doctorId'
      path: '/book/$doctorId'
      fullPath: '/patient/book/$doctorId'
      preLoaderRoute: typeof PatientBookDoctorIdRouteImport
      parentRoute: typeof PatientRoute
    }
    '/doctor/prescription/$id': {
      id: '/doctor/prescription/$id'
      path: '/prescription/$id'
      fullPath: '/doctor/prescription/$id'
      preLoaderRoute: typeof DoctorPrescriptionIdRouteImport
      parentRoute: typeof DoctorRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminCareCoordinationRoute: typeof AdminCareCoordinationRoute
  AdminDoctorsRoute: typeof AdminDoctorsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPostsRoute: typeof AdminPostsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminCareCoordinationRoute: AdminCareCoordinationRoute,
  AdminDoctorsRoute: AdminDoctorsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPostsRoute: AdminPostsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DoctorRouteChildren {
  DoctorAppointmentsRoute: typeof DoctorAppointmentsRoute
  DoctorCareCoordinationRoute: typeof DoctorCareCoordinationRoute
  DoctorPostsRoute: typeof DoctorPostsRoute
  DoctorProfileRoute: typeof DoctorProfileRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
  DoctorPrescriptionIdRoute: typeof DoctorPrescriptionIdRoute
}

const DoctorRouteChildren: DoctorRouteChildren = {
  DoctorAppointmentsRoute: DoctorAppointmentsRoute,
  DoctorCareCoordinationRoute: DoctorCareCoordinationRoute,
  DoctorPostsRoute: DoctorPostsRoute,
  DoctorProfileRoute: DoctorProfileRoute,
  DoctorIndexRoute: DoctorIndexRoute,
  DoctorPrescriptionIdRoute: DoctorPrescriptionIdRoute,
}

const DoctorRouteWithChildren =
  DoctorRoute._addFileChildren(DoctorRouteChildren)

interface PatientDoctorsRouteChildren {
  PatientDoctorsIdRoute: typeof PatientDoctorsIdRoute
}

const PatientDoctorsRouteChildren: PatientDoctorsRouteChildren = {
  PatientDoctorsIdRoute: PatientDoctorsIdRoute,
}

const PatientDoctorsRouteWithChildren = PatientDoctorsRoute._addFileChildren(
  PatientDoctorsRouteChildren,
)

interface PatientRouteChildren {
  PatientAppointmentsRoute: typeof PatientAppointmentsRoute
  PatientDoctorsRoute: typeof PatientDoctorsRouteWithChildren
  PatientPrescriptionsRoute: typeof PatientPrescriptionsRoute
  PatientProfileRoute: typeof PatientProfileRoute
  PatientIndexRoute: typeof PatientIndexRoute
  PatientBookDoctorIdRoute: typeof PatientBookDoctorIdRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientAppointmentsRoute: PatientAppointmentsRoute,
  PatientDoctorsRoute: PatientDoctorsRouteWithChildren,
  PatientPrescriptionsRoute: PatientPrescriptionsRoute,
  PatientProfileRoute: PatientProfileRoute,
  PatientIndexRoute: PatientIndexRoute,
  PatientBookDoctorIdRoute: PatientBookDoctorIdRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DoctorRoute: DoctorRouteWithChildren,
  PatientRoute: PatientRouteWithChildren,
  AuthAdminRoute: AuthAdminRoute,
  AuthDoctorRoute: AuthDoctorRoute,
  AuthPatientRoute: AuthPatientRoute,
  PrescriptionIdRoute: PrescriptionIdRoute,
  VideoIdRoute: VideoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
